apiVersion: v1
kind: Pod
metadata:
  name: ml-service1
  labels:
    app: ml-service1
    rel: stable
spec:
  containers:
  - name: mir-ml-service-1-api
    image: alexgiavaras/k8s_101_service_1:latest
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8002