apiVersion: v1
kind: Service
metadata:
  name: ml-inference-service
spec:
  type: LoadBalancer
  selector:
    app: ml-inference-service
  ports:
  - name: http
    port: 80
    nodePort: 30080
    targetPort: 8001
  - name: https
    port: 443
    nodePort: 30443
    targetPort: 8443
