apiVersion: v1
kind: Pod
metadata:
  name: ml-service2
  labels:
    app: ml-service2
    rel: stable
spec:
  containers:
  - name: mir-ml-service-2-api
    image: alexgiavaras/k8s_101_service_2:latest
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8003