apiVersion: v1
kind: Pod
metadata:
  name: ml-inference-service
  labels:
    app: ml-inference-service
    rel: stable
spec:
  containers:
  - name: ml-inference-service-api
    image: alexgiavaras/k8s_101_service_gateway:latest
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8001